#! /usr/bin/python3
#
# Quick and dirty converter from ING to ABN Amro format
# Saldo  12 May 13.199,19
import csv
import sys
import os
import argparse

def load_ing_file(infile):
    outrows=[]
    dates = {}
    with open(infile,'r') as ing:
        dialect = csv.Sniffer().sniff(ing.read(1024))
        ing.seek(0)
        print(dialect.delimiter)
        statement = csv.DictReader(ing,dialect=dialect)
        #statement=csv.reader(ing, dialect)
        # Convert the statement into something iterable
        print(statement)
        inrows = [x for x in statement]
        # Reverse the order of elements (ING uses latest first)
        for inrow in inrows[::-1]:
            print(inrow)
            outrow = {}
            outrow['Transactiedatum'] = inrow['Datum']
            outrow['Rentedatum'] = inrow['Datum']
            bedragstr = inrow['Bedrag (EUR)']
            (euros, cent) = bedragstr.split(',')
            bedragcnt = 100*int(euros) + int(cent)
            if inrow['Af Bij'] == 'Af':
                bedragcnt = -1 * bedragcnt
            outrow['Beginsaldo'] = 0
            outrow['Eindsaldo'] = 0
            outrow['Transactiebedrag'] = bedragcnt
            outrow['Omschrijving'] = '"' + inrow['Naam / Omschrijving'] \
                                + " " + inrow['Mededelingen'] + '"'
            #print(outrow)
            outrows.append(outrow)

    return outrows
def write_abn_file( outfile, outrows):
    with open(outfile,'w') as abn:
        saldo = 0
        newsaldo = 0
        for row in outrows:
            abn.write("%s,%s,%.2f,%.2f,%.2f,%s\n" %\
            (row['Transactiedatum'],row['Rentedatum'], row['Beginsaldo']/100.0,
            row['Eindsaldo']/100.0,row['Transactiebedrag']/100.0,row['Omschrijving']))

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Convert to ABN format")
    parser.add_argument('-i', '--infile',type=str,required=True)
    parser.add_argument('-o', '--outfile', type=str)
    args = parser.parse_args()


    print(args.infile)
    
    outrows = load_ing_file(args.infile)

    if not args.outfile:
        args.outfile = "out-%s-%s.csv" % (outrows[0]['Transactiedatum'],outrows[-1]['Transactiedatum'])
    print(args.outfile)

        
    write_abn_file( args.outfile, outrows)
    
    
